#!/bin/bash
# pi/onboard.sh — One-shot new-profile setup (any box running the pipeline).
#
# Usage:
#   bash pi/onboard.sh --name=jane --pdf=/path/to/linkedin.pdf \
#       [--keywords="head of product,founder,AI"] \
#       [--locations="New York,Remote"] \
#       [--school="Cornell University"] \
#       [--telegram-chat=12345]
#
# After this:
#   - profiles/jane/ exists with linkedin.pdf, profile.md (parsed), search.yaml
#   - first render runs, here.now slug claimed and written back to search.yaml
#   - tomorrow's cron picks up the new profile automatically

set -euo pipefail
cd "$(dirname "$0")/.."

# --- parse args ---
NAME=""
PDF=""
KEYWORDS=""
LOCATIONS=""
SCHOOL=""
TELEGRAM_CHAT=""

for arg in "$@"; do
  case $arg in
    --name=*) NAME="${arg#--name=}";;
    --pdf=*) PDF="${arg#--pdf=}";;
    --keywords=*) KEYWORDS="${arg#--keywords=}";;
    --locations=*) LOCATIONS="${arg#--locations=}";;
    --school=*) SCHOOL="${arg#--school=}";;
    --telegram-chat=*) TELEGRAM_CHAT="${arg#--telegram-chat=}";;
    *) echo "unknown arg: $arg"; exit 1;;
  esac
done

if [ -z "$NAME" ] || [ -z "$PDF" ]; then
  echo "Usage: bash pi/onboard.sh --name=<slug> --pdf=<path> [--keywords=...] [--locations=...] [--school=...] [--telegram-chat=...]"
  exit 1
fi
if [ ! -f "$PDF" ]; then
  echo "PDF not found: $PDF"
  exit 1
fi
# Guard on profile.md, not the bare dir — the onboarding wizard writes
# .enrichment/prefs.json into the dir moments before/while this script starts.
if [ -f "profiles/$NAME/profile.md" ]; then
  echo "profiles/$NAME is already onboarded (profile.md exists). Delete it first to re-onboard."
  exit 1
fi
mkdir -p "profiles/$NAME"

# --- scaffold dirs ---
echo "1/5  Creating profiles/$NAME/"
mkdir -p "profiles/$NAME/output"
touch "profiles/$NAME/output/.gitkeep"
cp "$PDF" "profiles/$NAME/linkedin.pdf"

# --- parse PDF via Pi gateway ---
echo "2/5  Parsing PDF via exe-dev gateway (Claude Sonnet)..."
/bin/npm run parse-pdf --silent -- --profile="$NAME"

# --- emit search.yaml ---
echo "3/5  Writing profiles/$NAME/search.yaml"
KEYWORDS_BLOCK=$(echo "${KEYWORDS:-head of product,founder in residence,AI product}" | /usr/bin/tr ',' '\n' | /usr/bin/awk 'NF{print "  - \"" $0 "\""}')
LOCATIONS_BLOCK=$(echo "${LOCATIONS:-New York,Remote}" | /usr/bin/tr ',' '\n' | /usr/bin/awk 'NF{print "  - \"" $0 "\""}')

cat > "profiles/$NAME/search.yaml" <<EOF
# profiles/$NAME/search.yaml — auto-generated by onboard.sh on $(date -u +%F)

keywords:
$KEYWORDS_BLOCK

locations:
$LOCATIONS_BLOCK

posted_within_days: 14

experience_levels:
  - "Director"
  - "Executive"

exclude_companies: []

exclude_keywords:
  - "unpaid"
  - "internship"
  - "commission only"

max_results: 30

enrichment:
  enabled: true
  validate_listings: true
  alumni_network:
    enabled: true
    school: "$SCHOOL"
    label: "${SCHOOL%% *}ians"

# Telegram chat for this profile's morning ping. Leave empty to use the
# global TELEGRAM_CHAT_ID from .env.
telegram:
  chat_id: "$TELEGRAM_CHAT"

# publish.slug is auto-claimed on first render. Don't hand-edit unless
# you're migrating an existing here.now slug into this profile.
publish:
  slug: ""
EOF

# --- first render (claims here.now slug) ---
echo "4/5  First render + here.now publish (claims a slug)..."
set -a; . ./.env; set +a
/bin/npm run render --silent -- --profile="$NAME" || echo "render had errors — check above"

# --- confirm ---
echo "5/5  Done."
echo ""
echo "  Profile dir: profiles/$NAME/"
SLUG=$(/usr/bin/grep "^\s*slug:" "profiles/$NAME/search.yaml" | /usr/bin/awk -F'"' '{print $2}')
if [ -n "$SLUG" ]; then
  echo "  Live URL:    https://$SLUG.here.now/  (password not yet set — set via API or skip)"
fi
echo "  Next cron run will discover jobs for this profile at 0700 UTC."
