#!/usr/bin/env npx ts-node
// pi/profile-graph.ts — profile.md → .enrichment/graph.json (schools + employers).
//
// The warm-path enrichment (enrich-exa.ts) and the ATS watchlist (discover.ts)
// both key off the candidate's REAL network: every school they attended and
// every company they worked at. profile.md is generated by linkedin-parser with
// a fixed shape (## Experience / ## Education, one `**Org — Title**` or
// `**Org**` bold line per entry), so this is a deterministic parse — no LLM.
//
// Writes profiles/<name>/.enrichment/graph.json:
//   { generated_at, schools: [{name}], employers: [{name, title, current}] }
//
// Additive only; safe to re-run. Skips profiles without profile.md.

import * as fs from 'fs'
import * as path from 'path'

const ROOT = path.resolve(__dirname, '..')

interface Employer { name: string; title?: string; current: boolean }
interface Graph { generated_at: string; schools: { name: string }[]; employers: Employer[] }

function listProfiles(): string[] {
  return fs.readdirSync(path.join(ROOT, 'profiles'), { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== 'example').map((d) => d.name)
}

// "ls BLACKBEAN" → "BLACKBEAN"-style noise stays as-is; we only strip the
// trailing legal suffixes that wreck people-search queries.
function cleanOrg(name: string): string {
  return name.replace(/\s+(inc\.?|llc|ltd\.?|corp\.?|co\.?)$/i, '').trim()
}

function section(text: string, header: string): string {
  const lines = text.split('\n')
  const start = lines.findIndex((l) => l.trim().toLowerCase() === `## ${header}`.toLowerCase())
  if (start === -1) return ''
  const rest = lines.slice(start + 1)
  const end = rest.findIndex((l) => l.startsWith('## '))
  return rest.slice(0, end === -1 ? rest.length : end).join('\n')
}

function parseProfile(text: string): Omit<Graph, 'generated_at'> {
  const employers: Employer[] = []
  const seenEmp = new Set<string>()
  const expBlock = section(text, 'experience')
  // linkedin-parser has emitted two shapes over time:
  //   `**Company — Title**`              (whole line bold)
  //   `**Title** — Company, address ...` (bold closes after the title)
  // The date line below each entry tells us whether the role is current.
  const expLines = expBlock.split('\n')
  expLines.forEach((l, i) => {
    const m = l.match(/^\*\*(.+?)\*\*\s*(?:[—–]\s*(.+))?$/)
    if (!m) return
    let name: string
    let title: string | undefined
    if (m[2]) {
      title = m[1].trim()
      name = cleanOrg(m[2].split(',')[0])
    } else {
      const [org, t] = m[1].split(/\s+[—–]\s+/)
      name = cleanOrg(org || '')
      title = t?.trim() || undefined
    }
    if (!name || seenEmp.has(name.toLowerCase())) return
    seenEmp.add(name.toLowerCase())
    const next = (expLines[i + 1] || '') + (expLines[i + 2] || '')
    employers.push({ name, title, current: /present/i.test(next) })
  })

  const schools: { name: string }[] = []
  const seenSchool = new Set<string>()
  for (const l of section(text, 'education').split('\n')) {
    // School is the bold part in both shapes (`**School**` / `**School** — degree`).
    const m = l.match(/^\*\*(.+?)\*\*\s*(?:[—–].*)?$/)
    if (!m) continue
    const name = m[1].split(/\s+[—–]\s+/)[0].trim()
    // High schools make terrible alumni-search anchors — too generic, no
    // LinkedIn school pages worth querying. Keep universities/colleges only.
    if (/\bhigh school\b|\bsecondary\b/i.test(name)) continue
    if (!name || seenSchool.has(name.toLowerCase())) continue
    seenSchool.add(name.toLowerCase())
    schools.push({ name })
  }
  return { schools, employers }
}

function main(): void {
  const profileArg = (process.argv.find((a) => a.startsWith('--profile=')) || '').split('=')[1] || null
  const profiles = profileArg ? [profileArg] : listProfiles()
  for (const p of profiles) {
    const src = path.join(ROOT, 'profiles', p, 'profile.md')
    if (!fs.existsSync(src)) { console.log(`  ${p}: no profile.md — skip`); continue }
    const graph: Graph = { generated_at: new Date().toISOString().slice(0, 10), ...parseProfile(fs.readFileSync(src, 'utf-8')) }
    const dir = path.join(ROOT, 'profiles', p, '.enrichment')
    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(path.join(dir, 'graph.json'), JSON.stringify(graph, null, 2))
    console.log(`  ${p}: graph.json — ${graph.schools.length} school(s), ${graph.employers.length} employer(s)`)
  }
}
main()
